// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDGYB-_q5Q88oHOCA-ONvYGJ-ADZyLRJ0',
    appId: '1:586393677337:web:337465f62c54853a304488',
    messagingSenderId: '586393677337',
    projectId: 'babyshophub-9bb2b',
    authDomain: 'babyshophub-9bb2b.firebaseapp.com',
    storageBucket: 'babyshophub-9bb2b.appspot.com',
    measurementId: 'G-CBZ235H10P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3JBh4OonQ9jhjfD3q2qc9EFqD-YAIvog',
    appId: '1:586393677337:android:8dd80e4e9208aa21304488',
    messagingSenderId: '586393677337',
    projectId: 'babyshophub-9bb2b',
    storageBucket: 'babyshophub-9bb2b.appspot.com',
  );
}
